package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	rootDir, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error getting working directory: %v\n", err)
		os.Exit(1)
	}
	
	// Go up two directories (from cmd/reset to project root)
	if strings.HasSuffix(rootDir, "/cmd/reset") || strings.HasSuffix(rootDir, "\\cmd\\reset") {
		rootDir = filepath.Dir(filepath.Dir(rootDir))
	}

	err = filepath.Walk(rootDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			name := info.Name()
			if strings.HasPrefix(name, ".") ||
				name == "vendor" ||
				name == "node_modules" ||
				name == "cmd" ||
				name == "migrations" ||
				name == "profiles" ||
				name == "scripts" ||
				name == "staticlint" ||
				name == "api" ||
				name == "docker" ||
				name == "pkg" {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		processFile(path)
		return nil
	})

	if err != nil {
		fmt.Fprintf(os.Stderr, "Error walking directory: %v\n", err)
		os.Exit(1)
	}
}

func processFile(filePath string) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing file %s: %v\n", filePath, err)
		return
	}

	pkgPath := filepath.Dir(filePath)
	pkgName := node.Name.Name

	structs := findResettableStructs(node)

	if len(structs) == 0 {
		return
	}

	generatedContent := generateResetFile(pkgName, structs)

	formatted, err := format.Source([]byte(generatedContent))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error formatting generated code: %v\n", err)
		return
	}

	outputPath := filepath.Join(pkgPath, "reset.gen.go")
	err = os.WriteFile(outputPath, formatted, 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error writing file %s: %v\n", outputPath, err)
		return
	}
}

type StructInfo struct {
	Name       string
	Fields     []*FieldInfo
	HasPointer bool
}

type FieldInfo struct {
	Name     string
	TypeExpr ast.Expr
	HasReset bool
}

func findResettableStructs(node *ast.File) []*StructInfo {
	var structs []*StructInfo

	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}

		hasGenerateComment := false
		if genDecl.Doc != nil {
			for _, comment := range genDecl.Doc.List {
				if strings.TrimSpace(comment.Text) == "// generate:reset" {
					hasGenerateComment = true
					break
				}
			}
		}

		if !hasGenerateComment {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			fields := collectFields(structType)

			structs = append(structs, &StructInfo{
				Name:   typeSpec.Name.Name,
				Fields: fields,
			})
		}
	}

	return structs
}

func collectFields(structType *ast.StructType) []*FieldInfo {
	var fields []*FieldInfo

	if structType.Fields == nil {
		return fields
	}

	for _, field := range structType.Fields.List {
		if field.Names == nil {
			continue
		}

		for _, name := range field.Names {
			fields = append(fields, &FieldInfo{
				Name:     name.Name,
				TypeExpr: field.Type,
			})
		}
	}

	return fields
}

func generateResetFile(pkgName string, structs []*StructInfo) string {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by cmd/reset. DO NOT EDIT.\n")
	buf.WriteString("\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	for _, s := range structs {
		buf.WriteString(fmt.Sprintf("func (rs *%s) Reset() {\n", s.Name))
		buf.WriteString("\tif rs == nil {\n")
		buf.WriteString("\t\treturn\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\n")

		for _, field := range s.Fields {
			generateFieldReset(&buf, field)
		}

		buf.WriteString("}\n\n")
	}

	return buf.String()
}

func generateFieldReset(buf *bytes.Buffer, field *FieldInfo) {
	fieldName := field.Name
	typeExpr := field.TypeExpr

	fieldType := getTypeString(typeExpr)

	switch {
	case isPointerType(typeExpr):
		elemType := strings.TrimPrefix(fieldType, "*")
		buf.WriteString(fmt.Sprintf("\tif rs.%s != nil {\n", fieldName))
		buf.WriteString(fmt.Sprintf("\t\t*rs.%s = %s\n", fieldName, getZeroValue(elemType)))
		buf.WriteString("\t}\n")

	case isSliceType(typeExpr):
		buf.WriteString(fmt.Sprintf("\trs.%s = rs.%s[:0]\n", fieldName, fieldName))

	case isMapType(typeExpr):
		buf.WriteString(fmt.Sprintf("\tclear(rs.%s)\n", fieldName))

	case isBasicType(fieldType):
		buf.WriteString(fmt.Sprintf("\trs.%s = %s\n", fieldName, getZeroValue(fieldType)))

	default:
		if strings.HasPrefix(fieldType, "*") {
			buf.WriteString(fmt.Sprintf("\tif rs.%s != nil {\n", fieldName))
			buf.WriteString(fmt.Sprintf("\t\trs.%s.Reset()\n", fieldName))
			buf.WriteString("\t}\n")
		} else {
			buf.WriteString(fmt.Sprintf("\tif resetter, ok := rs.%s.(interface{ Reset() }); ok && rs.%s != nil {\n", fieldName, fieldName))
			buf.WriteString("\t\tresetter.Reset()\n")
			buf.WriteString("\t}\n")
		}
	}
}

func getTypeString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return getTypeString(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + getTypeString(t.X)
	case *ast.ArrayType:
		return "[]" + getTypeString(t.Elt)
	case *ast.MapType:
		return "map[" + getTypeString(t.Key) + "]" + getTypeString(t.Value)
	case *ast.InterfaceType:
		return "interface{}"
	default:
		return ""
	}
}

func isPointerType(expr ast.Expr) bool {
	_, ok := expr.(*ast.StarExpr)
	return ok
}

func isSliceType(expr ast.Expr) bool {
	if arr, ok := expr.(*ast.ArrayType); ok {
		return arr.Len == nil
	}
	return false
}

func isMapType(expr ast.Expr) bool {
	_, ok := expr.(*ast.MapType)
	return ok
}

func isBasicType(typeStr string) bool {
	basicTypes := map[string]bool{
		"bool":       true,
		"string":     true,
		"int":        true,
		"int8":       true,
		"int16":      true,
		"int32":      true,
		"int64":      true,
		"uint":       true,
		"uint8":      true,
		"uint16":     true,
		"uint32":     true,
		"uint64":     true,
		"uintptr":    true,
		"float32":    true,
		"float64":    true,
		"complex64":  true,
		"complex128": true,
		"byte":       true,
		"rune":       true,
	}
	return basicTypes[typeStr]
}

func getZeroValue(typeStr string) string {
	switch typeStr {
	case "bool":
		return "false"
	case "string":
		return `""`
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64", "complex64", "complex128",
		"byte", "rune":
		return "0"
	default:
		return typeStr + "{}"
	}
}
