// Code generated by MockGen. DO NOT EDIT.
// Source: pool.go
//
// Generated by this command:
//
//	mockgen -source=pool.go -destination=pool_mock.go -package=pool
//

// Package pool is a generated GoMock package.
package pool

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockResetter is a mock of Resetter interface.
type MockResetter struct {
	ctrl     *gomock.Controller
	recorder *MockResetterMockRecorder
	isgomock struct{}
}

// MockResetterMockRecorder is the mock recorder for MockResetter.
type MockResetterMockRecorder struct {
	mock *MockResetter
}

// NewMockResetter creates a new mock instance.
func NewMockResetter(ctrl *gomock.Controller) *MockResetter {
	mock := &MockResetter{ctrl: ctrl}
	mock.recorder = &MockResetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResetter) EXPECT() *MockResetterMockRecorder {
	return m.recorder
}

// Reset mocks base method.
func (m *MockResetter) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockResetterMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockResetter)(nil).Reset))
}
